;задание 1.1
(defun insert (X N List)
   (cond ((NULL LIST) (cons X List))
      ((eq N 1) (cons X List))
      (T (cons (car List)
            (insert X (- N 1) (CDR List))
         )
      )
   )
)
(print"Исходный список: ")
(print "5 2 4 1 8 10 3 15")
(print"Полученный список: ")
(print (insert 66 6 '(5 2 4 1 8 10 3 15)))
