;задание 1.1
(defun insert (X N LST)
   (cond ((NULL LST) (cons X LST))
      ((eq N 1) (cons X LST))
      (T (cons (car LST)
            (insert X (- N 1) (CDR LST))
         )
      )
   )
)
(print"Исходный список: ")
(print "5 2 4 1 8 10 3 15")
(print"Полученный список: ")
(print (insert 66 6 '(5 2 4 1 8 10 3 15)))
