;задание 1.2
(defun Delete (N List)
   (COND ((EQ N 1) (CDR List))
      (T (CONS (CAR List)
            (Delete (- N 1) (CDR List))
         )
      )
   )
)
(print (Delete 2 '(1 4 6 23 12 5 71 8)))
